-- MySQL Script generated by MySQL Workbench
-- Sun Apr 20 12:29:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema TA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TA` ;

-- -----------------------------------------------------
-- Schema TA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TA`;
USE `TA` ;

-- -----------------------------------------------------
-- Table `TA`.`Biblioteca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`Biblioteca` (
  `idBiblioteca` INT NOT NULL AUTO_INCREMENT,
  `ingresoTotal` DOUBLE NULL DEFAULT NULL,
  `cantidadDeJuegos` INT NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idBiblioteca`)
  )ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TA`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `contrasena` VARCHAR(100) NULL DEFAULT NULL,
  `fechaRegistro` DATE NULL DEFAULT NULL,
  `telefono` INT NULL DEFAULT NULL,
  `fotoDePerfil` BLOB NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  `biblioteca_idBiblioteca` INT NOT NULL,
  `rol_idrol` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`biblioteca_idBiblioteca`) REFERENCES `TA`.`Biblioteca` (`idBiblioteca`),
  FOREIGN KEY (`rol_idrol`) REFERENCES `TA`.`Rol` (`idRol`)
  )ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TA`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`Administrador` (
  `idAdministrador` INT NOT NULL,
  `rol` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idAdministrador`),
  FOREIGN KEY (`idAdministrador`) REFERENCES `TA`.`Usuario` (`id`)
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TA`.`Jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`Jugador` (
  `idJugador` INT NOT NULL,
  `nickname` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idJugador`),
  FOREIGN KEY (`idJugador`) REFERENCES `TA`.`Usuario` (`id`)
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TA`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`Genero` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `nombreGenero` ENUM('ACCCION', 'ROL', 'ESTRATEGIA', 'SHOOTER', 'SIMULACION', 'DEPORTES', 'CARRERAS') NULL DEFAULT NULL,
  PRIMARY KEY (`idGenero`)
  )ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TA`.`ModeloNegocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`ModeloNegocio` (
  `idModeloNegocio` INT NOT NULL AUTO_INCREMENT,
  `modelo` ENUM('FREE_TO_PLAY', 'PAGA', 'SUSCRIPCION') NULL DEFAULT NULL,
  PRIMARY KEY (`idModeloNegocio`)
  )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TA`.`Desarrollador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`Desarrollador` (
  `idDesarrollador` INT NOT NULL,
  `numeroCuenta` INT NULL DEFAULT NULL,
  `ingresoTotal` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`idDesarrollador`),
  FOREIGN KEY (`idDesarrollador`) REFERENCES `TA`.`Usuario` (`id`)
    )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TA`.`Juego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`Juego` (
  `idJuego` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DOUBLE NULL DEFAULT NULL,
  `version` DOUBLE NULL DEFAULT NULL,
  `imagenJuego` BLOB NULL DEFAULT NULL,
  `fechaLanzamiento` DATE NULL DEFAULT NULL,
  `requisitosMinimos` TEXT NULL DEFAULT NULL,
  `requisitosRecomendados` TEXT NULL DEFAULT NULL,
  `espacioDisco` DOUBLE NULL DEFAULT NULL,
  `fechaUltimaActualizacion` DATE NULL DEFAULT NULL,
  `genero_idGenero` INT NOT NULL,
  `modeloNegocio_idModeloNegocio` INT NOT NULL,
  `desarrollador_idDesarrollador` INT NOT NULL,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idJuego`),
    FOREIGN KEY (`genero_idGenero`) REFERENCES `TA`.`Genero` (`idGenero`),
    FOREIGN KEY (`modeloNegocio_idModeloNegocio`) REFERENCES `TA`.`ModeloNegocio` (`idModeloNegocio`),
    FOREIGN KEY (`desarrollador_idDesarrollador`) REFERENCES `TA`.`Desarrollador` (`idDesarrollador`)
    )ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TA`.`Calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`Calificacion` (
  `idCalificacion` INT NOT NULL,
  `fidJugador` INT NULL DEFAULT NULL,
  `fidJuego` INT NULL DEFAULT NULL,
  `fechaPuntuacion` DATE NULL DEFAULT NULL,
  `puntaje` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idCalificacion`),
  FOREIGN KEY (`fidJugador`) REFERENCES `TA`.`Jugador` (`idJugador`),
  FOREIGN KEY (`fidJuego`) REFERENCES `TA`.`Juego` (`idJuego`)
  )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TA`.`CarroCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`CarroCompra` (
  `totalEstimado` DOUBLE NULL DEFAULT NULL,
  `jugador_idJugador` INT NOT NULL,
  `idCarroCompra` INT NOT NULL,
  PRIMARY KEY (`idCarroCompra`),
  FOREIGN KEY (`jugador_idJugador`) REFERENCES `TA`.`Jugador` (`idJugador`)
  )ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TA`.`Cartera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`Cartera` (
  `saldoActual` DOUBLE NULL DEFAULT NULL,
  `jugador_idJugador` INT NOT NULL,
  `idCartera` INT NOT NULL,
  PRIMARY KEY (`idCartera`),
  FOREIGN KEY (`jugador_idJugador`) REFERENCES `TA`.`Jugador` (`idJugador`)
  )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TA`.`JuegoAdquirido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`JuegoAdquirido` (
  `fidBiblioteca` INT NULL DEFAULT NULL,
  `fidJuego` INT NULL DEFAULT NULL,
  `fechaAdquisicion` DATE NULL DEFAULT NULL,
  `ultimaSesion` DATE NULL DEFAULT NULL,
  `tiempoJuego` DOUBLE NULL DEFAULT NULL,
  `actualizado` TINYINT(1) NULL DEFAULT NULL,
    FOREIGN KEY (`fidBiblioteca`) REFERENCES `TA`.`Biblioteca` (`idBiblioteca`),
    FOREIGN KEY (`fidJuego`) REFERENCES `TA`.`Juego` (`idJuego`)
    )ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `TA`.`MetodoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`MetodoPago` (
  `idMetodo` INT NOT NULL AUTO_INCREMENT,
  `nombreMetodo` ENUM('Visa', 'Mastercard', 'PagoEfectivo', 'PayValido') NULL DEFAULT NULL,
  PRIMARY KEY (`idMetodo`)
  )ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TA`.`Recarga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`Recarga` (
  `idRecarga` INT NOT NULL AUTO_INCREMENT,
  `fechaRecarga` DATE NULL DEFAULT NULL,
  `monto` DOUBLE NULL DEFAULT NULL,
  `metodoPago_idMetodo` INT NOT NULL,
  `cartera_IdCartera` INT NOT NULL,
  PRIMARY KEY (`idRecarga`),
  FOREIGN KEY (`metodoPago_idMetodo`) REFERENCES `TA`.`MetodoPago` (`idMetodo`),
  FOREIGN KEY (`cartera_IdCartera`) REFERENCES `TA`.`Cartera` (`idCartera`)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TA`.`Reseña`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`Reseña` (
  `fidJugador` INT NULL DEFAULT NULL,
  `fidJuego` INT NULL DEFAULT NULL,
  `calificacion` INT NULL DEFAULT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  `fechaPublicacion` DATE NULL DEFAULT NULL,
  `autor` INT NULL DEFAULT NULL,
  `idJuego` INT NULL DEFAULT NULL,
  `calificacion_IdCalificacion` INT NOT NULL,
    FOREIGN KEY (`autor`) REFERENCES `TA`.`Jugador` (`idJugador`),
    FOREIGN KEY (`fidJuego`) REFERENCES `TA`.`Juego` (`idJuego`),
    FOREIGN KEY (`calificacion_IdCalificacion`) REFERENCES `TA`.`Calificacion` (`idCalificacion`)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TA`.`CarroCompraXJuego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`CarroCompraXJuego` (
  `carroCompra_IdCarroCompra` INT NOT NULL,
  `juego_idJuego` INT NOT NULL,
  PRIMARY KEY (`carroCompra_IdCarroCompra`, `Juego_idJuego`),
  FOREIGN KEY (`carroCompra_IdCarroCompra`) REFERENCES `TA`.`CarroCompra` (`idCarroCompra`),
  FOREIGN KEY (`juego_idJuego`) REFERENCES `TA`.`Juego` (`idJuego`)
)ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TA`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TA`.`Rol` (
  `idRol` INT NOT NULL,
  `nombreRol` ENUM('Jugador', 'Administrador', 'Desarrollador'),
  PRIMARY KEY (`idRol`)
)ENGINE = InnoDB;

INSERT INTO `TA`.`Rol`(idRol,nombreRol) VALUES(1,'Jugador');
INSERT INTO `TA`.`Rol`(idRol,nombreRol) VALUES(2,'Administrador');
INSERT INTO `TA`.`Rol`(idRol,nombreRol) VALUES(3,'Desarrollador');
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

