//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagStoreWA.ServiciosWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", ConfigurationName="ServiciosWS.DesarrolladorWS")]
    public interface DesarrolladorWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/obtenerDesarrolladorPorIDReque" +
            "st", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/obtenerDesarrolladorPorIDRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LagStoreWA.ServiciosWS.obtenerDesarrolladorPorIDResponse obtenerDesarrolladorPorID(LagStoreWA.ServiciosWS.obtenerDesarrolladorPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/obtenerDesarrolladorPorIDReque" +
            "st", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/obtenerDesarrolladorPorIDRespo" +
            "nse")]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.obtenerDesarrolladorPorIDResponse> obtenerDesarrolladorPorIDAsync(LagStoreWA.ServiciosWS.obtenerDesarrolladorPorIDRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/eliminarDesarrolladorRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/eliminarDesarrolladorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LagStoreWA.ServiciosWS.eliminarDesarrolladorResponse eliminarDesarrollador(LagStoreWA.ServiciosWS.eliminarDesarrolladorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/eliminarDesarrolladorRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/eliminarDesarrolladorResponse")]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.eliminarDesarrolladorResponse> eliminarDesarrolladorAsync(LagStoreWA.ServiciosWS.eliminarDesarrolladorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/insertarDesarrolladorRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/insertarDesarrolladorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LagStoreWA.ServiciosWS.insertarDesarrolladorResponse insertarDesarrollador(LagStoreWA.ServiciosWS.insertarDesarrolladorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/insertarDesarrolladorRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/insertarDesarrolladorResponse")]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.insertarDesarrolladorResponse> insertarDesarrolladorAsync(LagStoreWA.ServiciosWS.insertarDesarrolladorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/modificarDesarrolladorRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/modificarDesarrolladorResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LagStoreWA.ServiciosWS.modificarDesarrolladorResponse modificarDesarrollador(LagStoreWA.ServiciosWS.modificarDesarrolladorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/modificarDesarrolladorRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/modificarDesarrolladorResponse" +
            "")]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.modificarDesarrolladorResponse> modificarDesarrolladorAsync(LagStoreWA.ServiciosWS.modificarDesarrolladorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/listarTodosDesarrolladoresRequ" +
            "est", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/listarTodosDesarrolladoresResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LagStoreWA.ServiciosWS.listarTodosDesarrolladoresResponse listarTodosDesarrolladores(LagStoreWA.ServiciosWS.listarTodosDesarrolladoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/listarTodosDesarrolladoresRequ" +
            "est", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/DesarrolladorWS/listarTodosDesarrolladoresResp" +
            "onse")]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.listarTodosDesarrolladoresResponse> listarTodosDesarrolladoresAsync(LagStoreWA.ServiciosWS.listarTodosDesarrolladoresRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/")]
    public partial class desarrollador : usuario {
        
        private int idDesarrolladorField;
        
        private double ingresoTotalField;
        
        private string numeroCuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idDesarrollador {
            get {
                return this.idDesarrolladorField;
            }
            set {
                this.idDesarrolladorField = value;
                this.RaisePropertyChanged("idDesarrollador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double ingresoTotal {
            get {
                return this.ingresoTotalField;
            }
            set {
                this.ingresoTotalField = value;
                this.RaisePropertyChanged("ingresoTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string numeroCuenta {
            get {
                return this.numeroCuentaField;
            }
            set {
                this.numeroCuentaField = value;
                this.RaisePropertyChanged("numeroCuenta");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(desarrollador))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jugador))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contrasenaField;
        
        private string emailField;
        
        private System.DateTime fechaRegistroField;
        
        private bool fechaRegistroFieldSpecified;
        
        private string fotoDePerfilField;
        
        private int idUsuarioField;
        
        private string nombreField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contrasena {
            get {
                return this.contrasenaField;
            }
            set {
                this.contrasenaField = value;
                this.RaisePropertyChanged("contrasena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaRegistro {
            get {
                return this.fechaRegistroField;
            }
            set {
                this.fechaRegistroField = value;
                this.RaisePropertyChanged("fechaRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRegistroSpecified {
            get {
                return this.fechaRegistroFieldSpecified;
            }
            set {
                this.fechaRegistroFieldSpecified = value;
                this.RaisePropertyChanged("fechaRegistroSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fotoDePerfil {
            get {
                return this.fotoDePerfilField;
            }
            set {
                this.fotoDePerfilField = value;
                this.RaisePropertyChanged("fotoDePerfil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
                this.RaisePropertyChanged("idUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/")]
    public partial class resena : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private jugador autorField;
        
        private calificacion calificacionField;
        
        private string comentarioField;
        
        private System.DateTime fechaPublicacionField;
        
        private bool fechaPublicacionFieldSpecified;
        
        private int idResenaField;
        
        private juego juegoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public jugador autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("autor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public calificacion calificacion {
            get {
                return this.calificacionField;
            }
            set {
                this.calificacionField = value;
                this.RaisePropertyChanged("calificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string comentario {
            get {
                return this.comentarioField;
            }
            set {
                this.comentarioField = value;
                this.RaisePropertyChanged("comentario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaPublicacion {
            get {
                return this.fechaPublicacionField;
            }
            set {
                this.fechaPublicacionField = value;
                this.RaisePropertyChanged("fechaPublicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaPublicacionSpecified {
            get {
                return this.fechaPublicacionFieldSpecified;
            }
            set {
                this.fechaPublicacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaPublicacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idResena {
            get {
                return this.idResenaField;
            }
            set {
                this.idResenaField = value;
                this.RaisePropertyChanged("idResena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public juego juego {
            get {
                return this.juegoField;
            }
            set {
                this.juegoField = value;
                this.RaisePropertyChanged("juego");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/")]
    public partial class jugador : usuario {
        
        private calificacion[] calificacionesField;
        
        private carroCompra carroCompraField;
        
        private cartera carteraField;
        
        private int idJugadorField;
        
        private string nicknameField;
        
        private resena[] resenasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("calificaciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public calificacion[] calificaciones {
            get {
                return this.calificacionesField;
            }
            set {
                this.calificacionesField = value;
                this.RaisePropertyChanged("calificaciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public carroCompra carroCompra {
            get {
                return this.carroCompraField;
            }
            set {
                this.carroCompraField = value;
                this.RaisePropertyChanged("carroCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public cartera cartera {
            get {
                return this.carteraField;
            }
            set {
                this.carteraField = value;
                this.RaisePropertyChanged("cartera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idJugador {
            get {
                return this.idJugadorField;
            }
            set {
                this.idJugadorField = value;
                this.RaisePropertyChanged("idJugador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nickname {
            get {
                return this.nicknameField;
            }
            set {
                this.nicknameField = value;
                this.RaisePropertyChanged("nickname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resenas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public resena[] resenas {
            get {
                return this.resenasField;
            }
            set {
                this.resenasField = value;
                this.RaisePropertyChanged("resenas");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/")]
    public partial class calificacion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private jugador autorField;
        
        private System.DateTime fechaPuntuacionField;
        
        private bool fechaPuntuacionFieldSpecified;
        
        private int idCalificacionField;
        
        private juego juegoField;
        
        private int puntuacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public jugador autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("autor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaPuntuacion {
            get {
                return this.fechaPuntuacionField;
            }
            set {
                this.fechaPuntuacionField = value;
                this.RaisePropertyChanged("fechaPuntuacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaPuntuacionSpecified {
            get {
                return this.fechaPuntuacionFieldSpecified;
            }
            set {
                this.fechaPuntuacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaPuntuacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCalificacion {
            get {
                return this.idCalificacionField;
            }
            set {
                this.idCalificacionField = value;
                this.RaisePropertyChanged("idCalificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public juego juego {
            get {
                return this.juegoField;
            }
            set {
                this.juegoField = value;
                this.RaisePropertyChanged("juego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int puntuacion {
            get {
                return this.puntuacionField;
            }
            set {
                this.puntuacionField = value;
                this.RaisePropertyChanged("puntuacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/")]
    public partial class juego : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private desarrollador desarrolladorField;
        
        private string descripcionField;
        
        private double espacioDiscoField;
        
        private System.DateTime fechaLanzamientoField;
        
        private bool fechaLanzamientoFieldSpecified;
        
        private System.DateTime fechaUltimaActualizacionField;
        
        private bool fechaUltimaActualizacionFieldSpecified;
        
        private genero generoField;
        
        private bool generoFieldSpecified;
        
        private int idJuegoField;
        
        private string imagenField;
        
        private modeloNegocio modeloNegocioField;
        
        private bool modeloNegocioFieldSpecified;
        
        private double precioField;
        
        private string requisitosMinimosField;
        
        private string requisitosRecomendadosField;
        
        private string tituloField;
        
        private double versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public desarrollador desarrollador {
            get {
                return this.desarrolladorField;
            }
            set {
                this.desarrolladorField = value;
                this.RaisePropertyChanged("desarrollador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double espacioDisco {
            get {
                return this.espacioDiscoField;
            }
            set {
                this.espacioDiscoField = value;
                this.RaisePropertyChanged("espacioDisco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaLanzamiento {
            get {
                return this.fechaLanzamientoField;
            }
            set {
                this.fechaLanzamientoField = value;
                this.RaisePropertyChanged("fechaLanzamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaLanzamientoSpecified {
            get {
                return this.fechaLanzamientoFieldSpecified;
            }
            set {
                this.fechaLanzamientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaLanzamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime fechaUltimaActualizacion {
            get {
                return this.fechaUltimaActualizacionField;
            }
            set {
                this.fechaUltimaActualizacionField = value;
                this.RaisePropertyChanged("fechaUltimaActualizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaUltimaActualizacionSpecified {
            get {
                return this.fechaUltimaActualizacionFieldSpecified;
            }
            set {
                this.fechaUltimaActualizacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaUltimaActualizacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public genero genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generoSpecified {
            get {
                return this.generoFieldSpecified;
            }
            set {
                this.generoFieldSpecified = value;
                this.RaisePropertyChanged("generoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int idJuego {
            get {
                return this.idJuegoField;
            }
            set {
                this.idJuegoField = value;
                this.RaisePropertyChanged("idJuego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string imagen {
            get {
                return this.imagenField;
            }
            set {
                this.imagenField = value;
                this.RaisePropertyChanged("imagen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public modeloNegocio modeloNegocio {
            get {
                return this.modeloNegocioField;
            }
            set {
                this.modeloNegocioField = value;
                this.RaisePropertyChanged("modeloNegocio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modeloNegocioSpecified {
            get {
                return this.modeloNegocioFieldSpecified;
            }
            set {
                this.modeloNegocioFieldSpecified = value;
                this.RaisePropertyChanged("modeloNegocioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string requisitosMinimos {
            get {
                return this.requisitosMinimosField;
            }
            set {
                this.requisitosMinimosField = value;
                this.RaisePropertyChanged("requisitosMinimos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string requisitosRecomendados {
            get {
                return this.requisitosRecomendadosField;
            }
            set {
                this.requisitosRecomendadosField = value;
                this.RaisePropertyChanged("requisitosRecomendados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public double version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/")]
    public enum genero {
        
        /// <remarks/>
        Accion,
        
        /// <remarks/>
        Rol,
        
        /// <remarks/>
        Estrategia,
        
        /// <remarks/>
        Shooter,
        
        /// <remarks/>
        Simulación,
        
        /// <remarks/>
        Deportes,
        
        /// <remarks/>
        Carreras,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/")]
    public enum modeloNegocio {
        
        /// <remarks/>
        Free_to_play,
        
        /// <remarks/>
        Paga,
        
        /// <remarks/>
        Suscripcion,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/")]
    public partial class carroCompra : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private int idCarroCompraField;
        
        private juego[] juegosField;
        
        private jugador jugadorField;
        
        private double totalEstimadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCarroCompra {
            get {
                return this.idCarroCompraField;
            }
            set {
                this.idCarroCompraField = value;
                this.RaisePropertyChanged("idCarroCompra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("juegos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public juego[] juegos {
            get {
                return this.juegosField;
            }
            set {
                this.juegosField = value;
                this.RaisePropertyChanged("juegos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public jugador jugador {
            get {
                return this.jugadorField;
            }
            set {
                this.jugadorField = value;
                this.RaisePropertyChanged("jugador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double totalEstimado {
            get {
                return this.totalEstimadoField;
            }
            set {
                this.totalEstimadoField = value;
                this.RaisePropertyChanged("totalEstimado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/")]
    public partial class cartera : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private recarga[] historialField;
        
        private int idCarteraField;
        
        private jugador jugadorField;
        
        private double saldoActualField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("historial", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public recarga[] historial {
            get {
                return this.historialField;
            }
            set {
                this.historialField = value;
                this.RaisePropertyChanged("historial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idCartera {
            get {
                return this.idCarteraField;
            }
            set {
                this.idCarteraField = value;
                this.RaisePropertyChanged("idCartera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public jugador jugador {
            get {
                return this.jugadorField;
            }
            set {
                this.jugadorField = value;
                this.RaisePropertyChanged("jugador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double saldoActual {
            get {
                return this.saldoActualField;
            }
            set {
                this.saldoActualField = value;
                this.RaisePropertyChanged("saldoActual");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/")]
    public partial class recarga : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activoField;
        
        private cartera carteraField;
        
        private System.DateTime fechaRecargaField;
        
        private bool fechaRecargaFieldSpecified;
        
        private int idRecargaField;
        
        private metodoPago metodoPagoField;
        
        private bool metodoPagoFieldSpecified;
        
        private double montoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public cartera cartera {
            get {
                return this.carteraField;
            }
            set {
                this.carteraField = value;
                this.RaisePropertyChanged("cartera");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaRecarga {
            get {
                return this.fechaRecargaField;
            }
            set {
                this.fechaRecargaField = value;
                this.RaisePropertyChanged("fechaRecarga");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaRecargaSpecified {
            get {
                return this.fechaRecargaFieldSpecified;
            }
            set {
                this.fechaRecargaFieldSpecified = value;
                this.RaisePropertyChanged("fechaRecargaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idRecarga {
            get {
                return this.idRecargaField;
            }
            set {
                this.idRecargaField = value;
                this.RaisePropertyChanged("idRecarga");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public metodoPago metodoPago {
            get {
                return this.metodoPagoField;
            }
            set {
                this.metodoPagoField = value;
                this.RaisePropertyChanged("metodoPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool metodoPagoSpecified {
            get {
                return this.metodoPagoFieldSpecified;
            }
            set {
                this.metodoPagoFieldSpecified = value;
                this.RaisePropertyChanged("metodoPagoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("monto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/")]
    public enum metodoPago {
        
        /// <remarks/>
        Visa,
        
        /// <remarks/>
        Mastercard,
        
        /// <remarks/>
        PagoEfectivo,
        
        /// <remarks/>
        PayValido,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDesarrolladorPorID", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class obtenerDesarrolladorPorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDesarrollador;
        
        public obtenerDesarrolladorPorIDRequest() {
        }
        
        public obtenerDesarrolladorPorIDRequest(int idDesarrollador) {
            this.idDesarrollador = idDesarrollador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerDesarrolladorPorIDResponse", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class obtenerDesarrolladorPorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LagStoreWA.ServiciosWS.desarrollador @return;
        
        public obtenerDesarrolladorPorIDResponse() {
        }
        
        public obtenerDesarrolladorPorIDResponse(LagStoreWA.ServiciosWS.desarrollador @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDesarrollador", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class eliminarDesarrolladorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDesarrollador;
        
        public eliminarDesarrolladorRequest() {
        }
        
        public eliminarDesarrolladorRequest(int idDesarrollador) {
            this.idDesarrollador = idDesarrollador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarDesarrolladorResponse", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class eliminarDesarrolladorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarDesarrolladorResponse() {
        }
        
        public eliminarDesarrolladorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarDesarrollador", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class insertarDesarrolladorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LagStoreWA.ServiciosWS.desarrollador desarrollador;
        
        public insertarDesarrolladorRequest() {
        }
        
        public insertarDesarrolladorRequest(LagStoreWA.ServiciosWS.desarrollador desarrollador) {
            this.desarrollador = desarrollador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarDesarrolladorResponse", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class insertarDesarrolladorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarDesarrolladorResponse() {
        }
        
        public insertarDesarrolladorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarDesarrollador", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class modificarDesarrolladorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LagStoreWA.ServiciosWS.desarrollador desarrollador;
        
        public modificarDesarrolladorRequest() {
        }
        
        public modificarDesarrolladorRequest(LagStoreWA.ServiciosWS.desarrollador desarrollador) {
            this.desarrollador = desarrollador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarDesarrolladorResponse", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class modificarDesarrolladorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarDesarrolladorResponse() {
        }
        
        public modificarDesarrolladorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosDesarrolladores", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class listarTodosDesarrolladoresRequest {
        
        public listarTodosDesarrolladoresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosDesarrolladoresResponse", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class listarTodosDesarrolladoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LagStoreWA.ServiciosWS.desarrollador[] @return;
        
        public listarTodosDesarrolladoresResponse() {
        }
        
        public listarTodosDesarrolladoresResponse(LagStoreWA.ServiciosWS.desarrollador[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DesarrolladorWSChannel : LagStoreWA.ServiciosWS.DesarrolladorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DesarrolladorWSClient : System.ServiceModel.ClientBase<LagStoreWA.ServiciosWS.DesarrolladorWS>, LagStoreWA.ServiciosWS.DesarrolladorWS {
        
        public DesarrolladorWSClient() {
        }
        
        public DesarrolladorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DesarrolladorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DesarrolladorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DesarrolladorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LagStoreWA.ServiciosWS.obtenerDesarrolladorPorIDResponse LagStoreWA.ServiciosWS.DesarrolladorWS.obtenerDesarrolladorPorID(LagStoreWA.ServiciosWS.obtenerDesarrolladorPorIDRequest request) {
            return base.Channel.obtenerDesarrolladorPorID(request);
        }
        
        public LagStoreWA.ServiciosWS.desarrollador obtenerDesarrolladorPorID(int idDesarrollador) {
            LagStoreWA.ServiciosWS.obtenerDesarrolladorPorIDRequest inValue = new LagStoreWA.ServiciosWS.obtenerDesarrolladorPorIDRequest();
            inValue.idDesarrollador = idDesarrollador;
            LagStoreWA.ServiciosWS.obtenerDesarrolladorPorIDResponse retVal = ((LagStoreWA.ServiciosWS.DesarrolladorWS)(this)).obtenerDesarrolladorPorID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.obtenerDesarrolladorPorIDResponse> LagStoreWA.ServiciosWS.DesarrolladorWS.obtenerDesarrolladorPorIDAsync(LagStoreWA.ServiciosWS.obtenerDesarrolladorPorIDRequest request) {
            return base.Channel.obtenerDesarrolladorPorIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.obtenerDesarrolladorPorIDResponse> obtenerDesarrolladorPorIDAsync(int idDesarrollador) {
            LagStoreWA.ServiciosWS.obtenerDesarrolladorPorIDRequest inValue = new LagStoreWA.ServiciosWS.obtenerDesarrolladorPorIDRequest();
            inValue.idDesarrollador = idDesarrollador;
            return ((LagStoreWA.ServiciosWS.DesarrolladorWS)(this)).obtenerDesarrolladorPorIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LagStoreWA.ServiciosWS.eliminarDesarrolladorResponse LagStoreWA.ServiciosWS.DesarrolladorWS.eliminarDesarrollador(LagStoreWA.ServiciosWS.eliminarDesarrolladorRequest request) {
            return base.Channel.eliminarDesarrollador(request);
        }
        
        public int eliminarDesarrollador(int idDesarrollador) {
            LagStoreWA.ServiciosWS.eliminarDesarrolladorRequest inValue = new LagStoreWA.ServiciosWS.eliminarDesarrolladorRequest();
            inValue.idDesarrollador = idDesarrollador;
            LagStoreWA.ServiciosWS.eliminarDesarrolladorResponse retVal = ((LagStoreWA.ServiciosWS.DesarrolladorWS)(this)).eliminarDesarrollador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.eliminarDesarrolladorResponse> LagStoreWA.ServiciosWS.DesarrolladorWS.eliminarDesarrolladorAsync(LagStoreWA.ServiciosWS.eliminarDesarrolladorRequest request) {
            return base.Channel.eliminarDesarrolladorAsync(request);
        }
        
        public System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.eliminarDesarrolladorResponse> eliminarDesarrolladorAsync(int idDesarrollador) {
            LagStoreWA.ServiciosWS.eliminarDesarrolladorRequest inValue = new LagStoreWA.ServiciosWS.eliminarDesarrolladorRequest();
            inValue.idDesarrollador = idDesarrollador;
            return ((LagStoreWA.ServiciosWS.DesarrolladorWS)(this)).eliminarDesarrolladorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LagStoreWA.ServiciosWS.insertarDesarrolladorResponse LagStoreWA.ServiciosWS.DesarrolladorWS.insertarDesarrollador(LagStoreWA.ServiciosWS.insertarDesarrolladorRequest request) {
            return base.Channel.insertarDesarrollador(request);
        }
        
        public int insertarDesarrollador(LagStoreWA.ServiciosWS.desarrollador desarrollador) {
            LagStoreWA.ServiciosWS.insertarDesarrolladorRequest inValue = new LagStoreWA.ServiciosWS.insertarDesarrolladorRequest();
            inValue.desarrollador = desarrollador;
            LagStoreWA.ServiciosWS.insertarDesarrolladorResponse retVal = ((LagStoreWA.ServiciosWS.DesarrolladorWS)(this)).insertarDesarrollador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.insertarDesarrolladorResponse> LagStoreWA.ServiciosWS.DesarrolladorWS.insertarDesarrolladorAsync(LagStoreWA.ServiciosWS.insertarDesarrolladorRequest request) {
            return base.Channel.insertarDesarrolladorAsync(request);
        }
        
        public System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.insertarDesarrolladorResponse> insertarDesarrolladorAsync(LagStoreWA.ServiciosWS.desarrollador desarrollador) {
            LagStoreWA.ServiciosWS.insertarDesarrolladorRequest inValue = new LagStoreWA.ServiciosWS.insertarDesarrolladorRequest();
            inValue.desarrollador = desarrollador;
            return ((LagStoreWA.ServiciosWS.DesarrolladorWS)(this)).insertarDesarrolladorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LagStoreWA.ServiciosWS.modificarDesarrolladorResponse LagStoreWA.ServiciosWS.DesarrolladorWS.modificarDesarrollador(LagStoreWA.ServiciosWS.modificarDesarrolladorRequest request) {
            return base.Channel.modificarDesarrollador(request);
        }
        
        public int modificarDesarrollador(LagStoreWA.ServiciosWS.desarrollador desarrollador) {
            LagStoreWA.ServiciosWS.modificarDesarrolladorRequest inValue = new LagStoreWA.ServiciosWS.modificarDesarrolladorRequest();
            inValue.desarrollador = desarrollador;
            LagStoreWA.ServiciosWS.modificarDesarrolladorResponse retVal = ((LagStoreWA.ServiciosWS.DesarrolladorWS)(this)).modificarDesarrollador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.modificarDesarrolladorResponse> LagStoreWA.ServiciosWS.DesarrolladorWS.modificarDesarrolladorAsync(LagStoreWA.ServiciosWS.modificarDesarrolladorRequest request) {
            return base.Channel.modificarDesarrolladorAsync(request);
        }
        
        public System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.modificarDesarrolladorResponse> modificarDesarrolladorAsync(LagStoreWA.ServiciosWS.desarrollador desarrollador) {
            LagStoreWA.ServiciosWS.modificarDesarrolladorRequest inValue = new LagStoreWA.ServiciosWS.modificarDesarrolladorRequest();
            inValue.desarrollador = desarrollador;
            return ((LagStoreWA.ServiciosWS.DesarrolladorWS)(this)).modificarDesarrolladorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LagStoreWA.ServiciosWS.listarTodosDesarrolladoresResponse LagStoreWA.ServiciosWS.DesarrolladorWS.listarTodosDesarrolladores(LagStoreWA.ServiciosWS.listarTodosDesarrolladoresRequest request) {
            return base.Channel.listarTodosDesarrolladores(request);
        }
        
        public LagStoreWA.ServiciosWS.desarrollador[] listarTodosDesarrolladores() {
            LagStoreWA.ServiciosWS.listarTodosDesarrolladoresRequest inValue = new LagStoreWA.ServiciosWS.listarTodosDesarrolladoresRequest();
            LagStoreWA.ServiciosWS.listarTodosDesarrolladoresResponse retVal = ((LagStoreWA.ServiciosWS.DesarrolladorWS)(this)).listarTodosDesarrolladores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.listarTodosDesarrolladoresResponse> LagStoreWA.ServiciosWS.DesarrolladorWS.listarTodosDesarrolladoresAsync(LagStoreWA.ServiciosWS.listarTodosDesarrolladoresRequest request) {
            return base.Channel.listarTodosDesarrolladoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.listarTodosDesarrolladoresResponse> listarTodosDesarrolladoresAsync() {
            LagStoreWA.ServiciosWS.listarTodosDesarrolladoresRequest inValue = new LagStoreWA.ServiciosWS.listarTodosDesarrolladoresRequest();
            return ((LagStoreWA.ServiciosWS.DesarrolladorWS)(this)).listarTodosDesarrolladoresAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", ConfigurationName="ServiciosWS.JugadorWS")]
    public interface JugadorWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/listarTodosJugadoresRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/listarTodosJugadoresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LagStoreWA.ServiciosWS.listarTodosJugadoresResponse listarTodosJugadores(LagStoreWA.ServiciosWS.listarTodosJugadoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/listarTodosJugadoresRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/listarTodosJugadoresResponse")]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.listarTodosJugadoresResponse> listarTodosJugadoresAsync(LagStoreWA.ServiciosWS.listarTodosJugadoresRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/obtenerJugadorPorIDRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/obtenerJugadorPorIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LagStoreWA.ServiciosWS.obtenerJugadorPorIDResponse obtenerJugadorPorID(LagStoreWA.ServiciosWS.obtenerJugadorPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/obtenerJugadorPorIDRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/obtenerJugadorPorIDResponse")]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.obtenerJugadorPorIDResponse> obtenerJugadorPorIDAsync(LagStoreWA.ServiciosWS.obtenerJugadorPorIDRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/modificarJugadorRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/modificarJugadorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LagStoreWA.ServiciosWS.modificarJugadorResponse modificarJugador(LagStoreWA.ServiciosWS.modificarJugadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/modificarJugadorRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/modificarJugadorResponse")]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.modificarJugadorResponse> modificarJugadorAsync(LagStoreWA.ServiciosWS.modificarJugadorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/eliminarJugadorRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/eliminarJugadorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LagStoreWA.ServiciosWS.eliminarJugadorResponse eliminarJugador(LagStoreWA.ServiciosWS.eliminarJugadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/eliminarJugadorRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/eliminarJugadorResponse")]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.eliminarJugadorResponse> eliminarJugadorAsync(LagStoreWA.ServiciosWS.eliminarJugadorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/insertarJugadorRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/insertarJugadorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(usuario))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        LagStoreWA.ServiciosWS.insertarJugadorResponse insertarJugador(LagStoreWA.ServiciosWS.insertarJugadorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/insertarJugadorRequest", ReplyAction="http://ws.rrhh.lagstore.com.edu.pe/JugadorWS/insertarJugadorResponse")]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.insertarJugadorResponse> insertarJugadorAsync(LagStoreWA.ServiciosWS.insertarJugadorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosJugadores", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class listarTodosJugadoresRequest {
        
        public listarTodosJugadoresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosJugadoresResponse", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class listarTodosJugadoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LagStoreWA.ServiciosWS.jugador[] @return;
        
        public listarTodosJugadoresResponse() {
        }
        
        public listarTodosJugadoresResponse(LagStoreWA.ServiciosWS.jugador[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerJugadorPorID", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class obtenerJugadorPorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idJugador;
        
        public obtenerJugadorPorIDRequest() {
        }
        
        public obtenerJugadorPorIDRequest(int idJugador) {
            this.idJugador = idJugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerJugadorPorIDResponse", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class obtenerJugadorPorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LagStoreWA.ServiciosWS.jugador @return;
        
        public obtenerJugadorPorIDResponse() {
        }
        
        public obtenerJugadorPorIDResponse(LagStoreWA.ServiciosWS.jugador @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarJugador", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class modificarJugadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LagStoreWA.ServiciosWS.jugador jugador;
        
        public modificarJugadorRequest() {
        }
        
        public modificarJugadorRequest(LagStoreWA.ServiciosWS.jugador jugador) {
            this.jugador = jugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarJugadorResponse", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class modificarJugadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarJugadorResponse() {
        }
        
        public modificarJugadorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarJugador", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class eliminarJugadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idJugador;
        
        public eliminarJugadorRequest() {
        }
        
        public eliminarJugadorRequest(int idJugador) {
            this.idJugador = idJugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarJugadorResponse", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class eliminarJugadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarJugadorResponse() {
        }
        
        public eliminarJugadorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarJugador", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class insertarJugadorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public LagStoreWA.ServiciosWS.jugador jugador;
        
        public insertarJugadorRequest() {
        }
        
        public insertarJugadorRequest(LagStoreWA.ServiciosWS.jugador jugador) {
            this.jugador = jugador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarJugadorResponse", WrapperNamespace="http://ws.rrhh.lagstore.com.edu.pe/", IsWrapped=true)]
    public partial class insertarJugadorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.rrhh.lagstore.com.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarJugadorResponse() {
        }
        
        public insertarJugadorResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JugadorWSChannel : LagStoreWA.ServiciosWS.JugadorWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JugadorWSClient : System.ServiceModel.ClientBase<LagStoreWA.ServiciosWS.JugadorWS>, LagStoreWA.ServiciosWS.JugadorWS {
        
        public JugadorWSClient() {
        }
        
        public JugadorWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JugadorWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JugadorWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JugadorWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LagStoreWA.ServiciosWS.listarTodosJugadoresResponse LagStoreWA.ServiciosWS.JugadorWS.listarTodosJugadores(LagStoreWA.ServiciosWS.listarTodosJugadoresRequest request) {
            return base.Channel.listarTodosJugadores(request);
        }
        
        public LagStoreWA.ServiciosWS.jugador[] listarTodosJugadores() {
            LagStoreWA.ServiciosWS.listarTodosJugadoresRequest inValue = new LagStoreWA.ServiciosWS.listarTodosJugadoresRequest();
            LagStoreWA.ServiciosWS.listarTodosJugadoresResponse retVal = ((LagStoreWA.ServiciosWS.JugadorWS)(this)).listarTodosJugadores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.listarTodosJugadoresResponse> LagStoreWA.ServiciosWS.JugadorWS.listarTodosJugadoresAsync(LagStoreWA.ServiciosWS.listarTodosJugadoresRequest request) {
            return base.Channel.listarTodosJugadoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.listarTodosJugadoresResponse> listarTodosJugadoresAsync() {
            LagStoreWA.ServiciosWS.listarTodosJugadoresRequest inValue = new LagStoreWA.ServiciosWS.listarTodosJugadoresRequest();
            return ((LagStoreWA.ServiciosWS.JugadorWS)(this)).listarTodosJugadoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LagStoreWA.ServiciosWS.obtenerJugadorPorIDResponse LagStoreWA.ServiciosWS.JugadorWS.obtenerJugadorPorID(LagStoreWA.ServiciosWS.obtenerJugadorPorIDRequest request) {
            return base.Channel.obtenerJugadorPorID(request);
        }
        
        public LagStoreWA.ServiciosWS.jugador obtenerJugadorPorID(int idJugador) {
            LagStoreWA.ServiciosWS.obtenerJugadorPorIDRequest inValue = new LagStoreWA.ServiciosWS.obtenerJugadorPorIDRequest();
            inValue.idJugador = idJugador;
            LagStoreWA.ServiciosWS.obtenerJugadorPorIDResponse retVal = ((LagStoreWA.ServiciosWS.JugadorWS)(this)).obtenerJugadorPorID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.obtenerJugadorPorIDResponse> LagStoreWA.ServiciosWS.JugadorWS.obtenerJugadorPorIDAsync(LagStoreWA.ServiciosWS.obtenerJugadorPorIDRequest request) {
            return base.Channel.obtenerJugadorPorIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.obtenerJugadorPorIDResponse> obtenerJugadorPorIDAsync(int idJugador) {
            LagStoreWA.ServiciosWS.obtenerJugadorPorIDRequest inValue = new LagStoreWA.ServiciosWS.obtenerJugadorPorIDRequest();
            inValue.idJugador = idJugador;
            return ((LagStoreWA.ServiciosWS.JugadorWS)(this)).obtenerJugadorPorIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LagStoreWA.ServiciosWS.modificarJugadorResponse LagStoreWA.ServiciosWS.JugadorWS.modificarJugador(LagStoreWA.ServiciosWS.modificarJugadorRequest request) {
            return base.Channel.modificarJugador(request);
        }
        
        public int modificarJugador(LagStoreWA.ServiciosWS.jugador jugador) {
            LagStoreWA.ServiciosWS.modificarJugadorRequest inValue = new LagStoreWA.ServiciosWS.modificarJugadorRequest();
            inValue.jugador = jugador;
            LagStoreWA.ServiciosWS.modificarJugadorResponse retVal = ((LagStoreWA.ServiciosWS.JugadorWS)(this)).modificarJugador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.modificarJugadorResponse> LagStoreWA.ServiciosWS.JugadorWS.modificarJugadorAsync(LagStoreWA.ServiciosWS.modificarJugadorRequest request) {
            return base.Channel.modificarJugadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.modificarJugadorResponse> modificarJugadorAsync(LagStoreWA.ServiciosWS.jugador jugador) {
            LagStoreWA.ServiciosWS.modificarJugadorRequest inValue = new LagStoreWA.ServiciosWS.modificarJugadorRequest();
            inValue.jugador = jugador;
            return ((LagStoreWA.ServiciosWS.JugadorWS)(this)).modificarJugadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LagStoreWA.ServiciosWS.eliminarJugadorResponse LagStoreWA.ServiciosWS.JugadorWS.eliminarJugador(LagStoreWA.ServiciosWS.eliminarJugadorRequest request) {
            return base.Channel.eliminarJugador(request);
        }
        
        public int eliminarJugador(int idJugador) {
            LagStoreWA.ServiciosWS.eliminarJugadorRequest inValue = new LagStoreWA.ServiciosWS.eliminarJugadorRequest();
            inValue.idJugador = idJugador;
            LagStoreWA.ServiciosWS.eliminarJugadorResponse retVal = ((LagStoreWA.ServiciosWS.JugadorWS)(this)).eliminarJugador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.eliminarJugadorResponse> LagStoreWA.ServiciosWS.JugadorWS.eliminarJugadorAsync(LagStoreWA.ServiciosWS.eliminarJugadorRequest request) {
            return base.Channel.eliminarJugadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.eliminarJugadorResponse> eliminarJugadorAsync(int idJugador) {
            LagStoreWA.ServiciosWS.eliminarJugadorRequest inValue = new LagStoreWA.ServiciosWS.eliminarJugadorRequest();
            inValue.idJugador = idJugador;
            return ((LagStoreWA.ServiciosWS.JugadorWS)(this)).eliminarJugadorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LagStoreWA.ServiciosWS.insertarJugadorResponse LagStoreWA.ServiciosWS.JugadorWS.insertarJugador(LagStoreWA.ServiciosWS.insertarJugadorRequest request) {
            return base.Channel.insertarJugador(request);
        }
        
        public int insertarJugador(LagStoreWA.ServiciosWS.jugador jugador) {
            LagStoreWA.ServiciosWS.insertarJugadorRequest inValue = new LagStoreWA.ServiciosWS.insertarJugadorRequest();
            inValue.jugador = jugador;
            LagStoreWA.ServiciosWS.insertarJugadorResponse retVal = ((LagStoreWA.ServiciosWS.JugadorWS)(this)).insertarJugador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.insertarJugadorResponse> LagStoreWA.ServiciosWS.JugadorWS.insertarJugadorAsync(LagStoreWA.ServiciosWS.insertarJugadorRequest request) {
            return base.Channel.insertarJugadorAsync(request);
        }
        
        public System.Threading.Tasks.Task<LagStoreWA.ServiciosWS.insertarJugadorResponse> insertarJugadorAsync(LagStoreWA.ServiciosWS.jugador jugador) {
            LagStoreWA.ServiciosWS.insertarJugadorRequest inValue = new LagStoreWA.ServiciosWS.insertarJugadorRequest();
            inValue.jugador = jugador;
            return ((LagStoreWA.ServiciosWS.JugadorWS)(this)).insertarJugadorAsync(inValue);
        }
    }
}
